document.writeln("<html lang=\'en\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'container-fluid bg-white py-3\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row no-gutters\'>");
document.writeln("					<div class=\'col-lg-4 col-sm-12 mb-sm-4 mb-lg-0\'>");
document.writeln("						<div class=\'d-flex flex-lg-column flex-sm-row justify-content-sm-around justify-content-lg-start\'>");
document.writeln("							<div><img src=\'../images/personal/xuezhe.png\'></div>");
document.writeln("<!--							<div><img src=\'img/footer/footerFont.png\'></div>-->");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-4 col-sm-12\'>");
document.writeln("						<div class=\'row no-gutters text-center\'>");
document.writeln("							<ul class=\'col list-unstyled\'>");
document.writeln("								<li><a class=\'text-dark\' href=\'#\'>帮助</a></li>");
document.writeln("								<li><a class=\'font_small text-muted\' href=\'#\'>新手指南</a></li>");
document.writeln("								<li><a class=\'font_small text-muted\' href=\'#\'>服务保障</a></li>");
document.writeln("								<li><a class=\'font_small text-muted\' href=\'#\'>常见问题</a></li>");
document.writeln("							</ul>");
document.writeln("<!--							<ul class=\'col list-unstyled\'>-->");
document.writeln("<!--								<li><a class=\'text-dark\' href=\'#\'>卖家帮助</a></li>-->");
document.writeln("<!--								<li><a class=\'font_small text-muted\' href=\'#\'>商家入驻</a></li>-->");
document.writeln("<!--								<li><a class=\'font_small text-muted\' href=\'#\'>商家后台</a></li>-->");
document.writeln("<!--							</ul>-->");
document.writeln("							<ul class=\'col list-unstyled\'>");
document.writeln("								<li><a class=\'text-dark\' href=\'#\'>关于我们</a></li>");
document.writeln("								<li><a class=\'font_small text-muted\' href=\'#\'>关于学者网</a></li>");
document.writeln("								<li><a class=\'font_small text-muted\' href=\'#\'>联系我们</a></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><img src=\'../images/footer/wechat.png\'></a>");
document.writeln("									<a href=\'#\'><img src=\'../images/footer/sinablog.png\'></a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-4 col-sm-12\'>");
document.writeln("						<div class=\'d-flex justify-content-center\'>");
document.writeln("							<div>");
document.writeln("								<p class=\'mb-1 text-center\'>学者网客户端</p>");
document.writeln("								<div class=\'mb-1\'><img src=\'../images/footer/ios.png\' alt=\'\'></div>");
document.writeln("								<div><img src=\'../images/footer/android.png\' alt=\'\'></div>");
document.writeln("							</div>");
document.writeln("							<img class=\'ml-2\' src=\'../images/footer/erweima.png\' alt=\'\'>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'font_small text-center mt-sm-3 mt-lg-0\'>©2020 学者网 版权所有</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");